TEST_DATUM={
    ('hin', '0'): {   'expected': '(= a (+ (^ v_{0} 0) (+ (^ v_{1} 0) (^ v_{2} 0))))',
                      'input': '(= a (+ 1 (+ 1 1)))'},
    ('vor', '0'): {'expected': '1', 'input': '(= a (^ b 0))'},
    ('hin', '1'): {'expected': '(= (^ a 1) (^ a 1))', 'input': '(= a a)'},
    ('vor', '1'): {'expected': '(= a b)', 'input': '(= a (^ b 1))'},
    ('hin', '2'): {   'expected': '(= a (^ b (+ c d)))',
                      'input': '(= a (* (^ b c) (^ b d)))'},
    ('vor', '2'): {   'expected': '(= a (* (^ b c) (^ b d)))',
                      'input': '(= a (^ b (+ c d)))'},
    ('hin', '3'): {   'expected': '(= a (^ (^ b c) d))',
                      'input': '(= a (^ b (* c d)))'},
    ('vor', '3'): {   'expected': '(= a (^ b (* c d)))',
                      'input': '(= a (^ (^ b c) d))'},
    ('hin', '4'): {   'expected': '(= a (* (^ b d) (^ c d)))',
                      'input': '(= a (^ (* b c) d))'},
    ('vor', '4'): {   'expected': '(= a (^ (* b d) c))',
                      'input': '(= a (* (^ b c) (^ d c)))'},
    ('hin', '5'): {   'expected': '(= a (^ b (- "0" c)))',
                      'input': '(= a (/ "1" (^ b c)))'},
    ('vor', '5'): {   'expected': '(= a (/ "1" (^ b c)))',
                      'input': '(= a (^ b (- "0" c)))'}}