TEST_DATUM={
    ('hin', '0'): {   'expected': '(= a (log b (* c d)))',
                      'input': '(= a (+ (log b c) (log b d)))'},
    ('vor', '0'): {   'expected': '(= a (+ (log a b) (log a c)))',
                      'input': '(= a (log a (* b c)))'},
    ('hin', '1'): {   'expected': '(= a (log b (/ c d)))',
                      'input': '(= a (- (log b c) (log b d)))'},
    ('vor', '1'): {   'expected': '(= a (- (log b c) (log b d)))',
                      'input': '(= a (log b (/ c d)))'},
    ('hin', '2'): {   'expected': '(= a (log c (^ d b)))',
                      'input': '(= a (* b (log c d)))'},
    ('vor', '2'): {   'expected': '(= a (* d (log b c)))',
                      'input': '(= a (log b (^ c d)))'},
    ('hin', '3'): {   'expected': '(= a (log b (nroot d c)))',
                      'input': '(= a (/ (log b c) d))'},
    ('vor', '3'): {   'expected': '(= a (/ (log b d) c))',
                      'input': '(= a (log b (nroot c d)))'},
    ('hin', '4'): {   'expected': '(= a (/ (log v_{0} c) (log v_{0} b)))',
                      'input': '(= a (log b c))'},
    ('vor', '4'): {   'expected': '(= a (log d c))',
                      'input': '(= a (/ (log b c) (log b d)))'},
    ('hin', '5'): {'expected': '(= a (log v_{0} v_{0}))', 'input': '(= a "1")'},
    ('vor', '5'): {'expected': '(= a "1")', 'input': '(= a (log b b))'},
    ('hin', '6'): {'expected': '(= a (log v_{0} "1"))', 'input': '(= a "0")'},
    ('vor', '6'): {'expected': '(= a "0")', 'input': '(= a (log b "1"))'}}